"""Shared field definitions; no company names, transaction amounts or deal dates."""
FIELDS = {
    "target": r'\b(?:Company|Target)\b',
    "parent_or_bidder": r'\b(?:Parent|Bidder|Acquiror)\b',
    "acquisition_vehicle": r'\b(?:Merger Sub|Bidder)\b',
    "guarantors_or_covered_parties": r'guarant(?:ee|or)|covered provisions|solely for the purposes',
    "agreement_date": r'(?:Agreement.{0,40}dated as of|On [A-Za-z]+ \d{1,2}, \d{4}.{0,350}entered into)',
    "transaction_type": r'voluntary public takeover offer|merge with and into',
    "consideration_per_share": r'(?:right to receive|consideration per.{0,55}|Offer Price.{0,80}|amount in cash equal to)\s*[$€]|[$€][\d,.]+\s+(?:in cash|per)',
    "consideration_type": r'cash consideration|in cash.{0,80}Consideration|Offer Price',
    "expected_closing_timing": r'(?:expected|expect|anticipat).{0,100}(?:clos|complet)|(?:clos|complet).{0,80}(?:expected|half of)',
    "outside_or_long_stop_date": r'Outside Date|Long[- ]Stop Date',
    "extension_dates_and_conditions": r'(?:extend|extension).{0,100}(?:Outside Date|Long.Stop Date)|Outside Date.{0,200}extend|later date.{0,40}BaFin',
    "offer_or_acceptance_period": r'Acceptance Period|acceptance period|Offer Period',
    "cure_periods": r'cure|remedied|uncured',
    "approval_or_tender_threshold": r'majority of.{0,150}(?:voting|outstanding|Shares)|at least 50%.{0,160}|Minimum Acceptance',
    "regulatory_approvals": r'Hart.Scott|Required Approvals|financial services regulatory approvals|Merger Filings|foreign direct investment',
    "no_injunction_condition": r'no.{0,100}(?:injunction|enjoin)|absence of any law or order|Legal Restraint',
    "material_adverse_effect": r'Material Adverse Effect|material adverse change',
    "remedy_limitations": r'Burdensome Condition|Substantial Detriment|nothing in this Agreement shall require.{0,100}remedy|adverse and material',
    "financing_condition": r'(?:not|no|neither).{0,200}(?:condition|contingent).{0,200}financ|financ.{0,140}(?:condition|contingent)',
    "target_termination_fee": r'Company.{0,90}(?:pay|termination fee)|Company Termination Fee|Termination Fee.{0,50}means',
    "parent_termination_fee": r'(?:Parent|Bidder).{0,100}(?:pay|termination fee)|Parent Termination Fee|Reverse Termination Fee',
    "fee_triggers_and_tails": r'termination fee|Termination Fee|within (?:12|twelve).{0,30}months',
    "superior_or_competing_proposals": r'Superior Proposal|Competing Proposal|competing offer|Acquisition Proposal',
    "board_recommendation": r'Change of Company Recommendation|change.{0,40}recommendation|withdraw.{0,35}support',
    "matching_rights": r'matching|Match Period|Notice Period|negotiate.{0,80}good faith|four.{0,20}Business Days',
    "termination_rights": r'right.{0,20}terminate|may be terminated|Termination by',
    "funding_sources": r'committed debt financing|existing cash balances|funds.{0,80}available|Debt Financing',
    "bridge_amount": r'bridge loan commitments|aggregate.{0,90}(?:Commitments|commitments)|Bridge Facility',
    "committed_financing_minimum": r'committed financing.{0,200}no less than|financing.{0,100}at least',
    "financing_maturity": r'364 days|Maturity Date|mature on',
    "interest_basis": r'EURIBOR|Term SOFR|bear interest|Applicable Rate',
    "financing_fees_and_stepups": r'duration fees?|commitment fee|funding fee|step.up',
    "refinancing_requirements": r'mandatory prepayment|refinance|refinancing|Mandatory Prepayments',
    "financing_conditions": r'Conditions to.{0,30}(?:Borrow|Credit)|Limited Conditionality|Debt Commitment Letter|conditions.{0,80}funding',
    "common_shares": r'each share.{0,150}common stock|consideration per.{0,50}Share|each Share',
    "vested_options": r'(?:vested|Company Option).{0,80}(?:Option|vested)|Options\.',
    "unvested_options": r'unvested.{0,80}Option|Option.{0,80}unvested',
    "rsus": r'RSU|restricted stock unit',
    "psus": r'PSU|performance stock unit',
    "restricted_stock": r'Company Restricted Stock|restricted stock award',
    "employee_stock_purchase_plan": r'Stock Purchase Plan|ESPP',
    "award_cohort_differences": r'granted prior to|granted in calendar|Pre-\d{4}|target performance|maximum performance',
}

QUESTIONS = {
    "consideration": ["consideration_per_share"],
    "approval": ["approval_or_tender_threshold"],
    "outside_date": ["outside_or_long_stop_date"],
    "extensions": ["extension_dates_and_conditions"],
    "fees": ["target_termination_fee", "parent_termination_fee"],
    "fee_triggers": ["fee_triggers_and_tails"],
    "awards": ["vested_options", "unvested_options", "rsus", "psus", "restricted_stock", "employee_stock_purchase_plan", "award_cohort_differences"],
    "regulatory": ["regulatory_approvals"],
    "financing_condition": ["financing_condition"],
    "financing": ["funding_sources", "bridge_amount", "committed_financing_minimum", "financing_maturity", "interest_basis", "financing_fees_and_stepups", "refinancing_requirements", "financing_conditions"],
    "remedies": ["remedy_limitations"],
    "deal_contingent_hedge": ["approval_or_tender_threshold", "outside_or_long_stop_date", "extension_dates_and_conditions", "remedy_limitations", "fee_triggers_and_tails", "financing_condition"],
}
